In [1]:
import sys
sys.path.insert(0, '../')
import pandas as pd
from helpers_finalizacion_carrera import estimacion_abandono, estimacion_egresados_2019_vs_2020

Planteamos la estimación de abandono y egreso según lo escrito en "Un estimador estadístico del abandono para carreras de la facultad de Ciencias Exactas y Naturales de la Universidad de Buenos Aires" por Calloni y Pustilnik.

## Física

In [2]:
total_egresados_por_anio_inscripcion_fisica, inscripciones_por_anio_fisica, calculo_fisica, calculo_15_años_fisica = estimacion_abandono('fisica', 'Licenciatura en Ciencias Físicas')

In [3]:
total_egresados_por_anio_inscripcion_fisica

    año_inscripcion_facultad  cantidad_egresados
0                       2005                  19
1                       2006                  15
2                       2007                  35
3                       2008                  29
4                       2009                  51
5                       2010                  42
6                       2011                  59
7                       2012                  61
8                       2013                  49
9                       2014                  42
10                      2015                  48
11                      2016                  46
12                      2017                  44
13                      2018                  34
14                      2019                  37
15                      2020                  29
16                      2021                  18

In [4]:
inscripciones_por_anio_fisica

    año_inscripcion_facultad  cantidad_inscripciones
0                       2005                      41
1                       2006                      31
2                       2007                      59
3                       2008                      52
4                       2009                      84
5                       2010                      79
6                       2011                     112
7                       2012                     139
8                       2013                     120
9                       2014                     118
10                      2015                     119
11                      2016                     120
12                      2017                     139
13                      2018                     136
14                      2019                     136
15                      2020                     142
16                      2021                     300
17                      2022                     202
18                      2023                     248
19                      2024                     237
20                      2025                     182

In [5]:
calculo_fisica

,año_inscripcion_facultad,cantidad_inscripciones,cantidad_egresados,tasa_egreso,abandono,tasa_abandono
0,2005,41,19.0,0.463415,22.0,0.536585
1,2006,31,15.0,0.483871,16.0,0.516129
2,2007,59,35.0,0.593220,24.0,0.406780
3,2008,52,29.0,0.557692,23.0,0.442308
4,2009,84,51.0,0.607143,33.0,0.392857
5,2010,79,42.0,0.531646,37.0,0.468354
6,2011,112,59.0,0.526786,53.0,0.473214
7,2012,139,61.0,0.438849,78.0,0.561151
8,2013,120,49.0,0.408333,71.0,0.591667
9,2014,118,42.0,0.355932,76.0,0.644068
10,2015,119,48.0,0.403361,71.0,0.596639
11,2016,120,46.0,0.383333,74.0,0.616667
12,2017,139,44.0,0.316547,95.0,0.683453
13,2018,136,34.0,0.250000,102.0,0.750000
14,2019,136,37.0,0.272059,99.0,0.727941
15,2020,142,29.0,0.204225,113.0,0.795775
16,2021,300,18.0,0.060000,282.0,0.940000
17,2022,202,NaN,NaN,NaN,NaN
18,2023,248,NaN,NaN,NaN,NaN
19,2024,237,NaN,NaN,NaN,NaN
20,2025,182,NaN,NaN,NaN,NaN

In [6]:
calculo_15_años_fisica[['año_inscripcion_facultad', 'cantidad_inscripciones', 'egresados_en_15_anios_o_menos', 'abandono_15_años', 'tasa_egreso_15_años_con_d', 'tasa_abandono_15_años_con_d', 'd_del_año', 'error_d']]

,año_inscripcion_facultad,cantidad_inscripciones,egresados_en_15_anios_o_menos,abandono_15_años,tasa_egreso_15_años_con_d,tasa_abandono_15_años_con_d,d_del_año,error_d
0,2005,41,17.0,24.0,0.422880,0.577120,0.048780,0.028894
1,2006,31,11.0,20.0,0.361895,0.638105,0.129032,0.109146
2,2007,59,34.0,25.0,0.587731,0.412269,0.016949,-0.002937
3,2008,52,29.0,23.0,0.568783,0.431217,0.000000,-0.019886
4,2009,84,51.0,33.0,0.619217,0.380783,0.000000,-0.019886
5,2010,79,42.0,37.0,0.542218,0.457782,0.000000,-0.019886
6,2011,112,59.0,53.0,0.537262,0.462738,0.000000,-0.019886

In [7]:
calculo_15_años_fisica['tasa_egreso_15_años_con_d'].mean()

np.float64(0.519997875950101)

In [8]:
calculo_15_años_fisica['tasa_abandono_15_años'].mean()

np.float64(0.4901413583999009)

## Biologia

In [9]:
total_egresados_por_anio_inscripcion_biologia, inscripciones_por_anio_biologia, calculo_biologia, calculo_15_años_biologia = estimacion_abandono('biologia', 'Licenciatura en Ciencias Biológicas')

In [10]:
calculo_biologia

,año_inscripcion_facultad,cantidad_inscripciones,cantidad_egresados,tasa_egreso,abandono,tasa_abandono
0,2005,132,55.0,0.416667,77.0,0.583333
1,2006,184,96.0,0.521739,88.0,0.478261
2,2007,243,160.0,0.658436,83.0,0.341564
3,2008,220,151.0,0.686364,69.0,0.313636
4,2009,237,124.0,0.523207,113.0,0.476793
5,2010,267,155.0,0.580524,112.0,0.419476
6,2011,266,124.0,0.466165,142.0,0.533835
7,2012,290,114.0,0.393103,176.0,0.606897
8,2013,317,107.0,0.337539,210.0,0.662461
9,2014,266,81.0,0.304511,185.0,0.695489
10,2015,286,93.0,0.325175,193.0,0.674825
11,2016,237,75.0,0.316456,162.0,0.683544
12,2017,258,86.0,0.333333,172.0,0.666667
13,2018,261,80.0,0.306513,181.0,0.693487
14,2019,271,107.0,0.394834,164.0,0.605166
15,2020,178,45.0,0.252809,133.0,0.747191
16,2021,451,13.0,0.028825,438.0,0.971175
17,2022,211,NaN,NaN,NaN,NaN
18,2023,274,NaN,NaN,NaN,NaN
19,2024,255,NaN,NaN,NaN,NaN
20,2025,265,NaN,NaN,NaN,NaN

In [11]:
calculo_15_años_biologia[['año_inscripcion_facultad', 'cantidad_inscripciones', 'egresados_en_15_anios_o_menos', 'abandono_15_años', 'tasa_egreso_15_años_con_d', 'tasa_abandono_15_años_con_d', 'd_del_año', 'error_d']]

,año_inscripcion_facultad,cantidad_inscripciones,egresados_en_15_anios_o_menos,abandono_15_años,tasa_egreso_15_años_con_d,tasa_abandono_15_años_con_d,d_del_año,error_d
0,2005,132,50.0,82.0,0.391381,0.608619,0.037879,0.004634
1,2006,184,89.0,95.0,0.499776,0.500224,0.038043,0.004799
2,2007,243,153.0,90.0,0.650561,0.349439,0.028807,-0.004438
3,2008,220,150.0,70.0,0.704485,0.295515,0.004545,-0.028699
4,2009,237,122.0,115.0,0.531881,0.468119,0.008439,-0.024806
5,2010,267,152.0,115.0,0.588214,0.411786,0.011236,-0.022009
6,2011,266,124.0,142.0,0.481663,0.518337,0.000000,-0.033245

In [12]:
calculo_15_años_biologia['tasa_egreso_15_años_con_d'].mean()

np.float64(0.5497087654946886)

In [13]:
calculo_15_años_biologia['tasa_abandono_15_años'].mean()

np.float64(0.46797813172200026)

## Computacion

In [14]:
total_egresados_por_anio_inscripcion_computacion, inscripciones_por_anio_computacion, calculo_computacion, calculo_15_años_computacion = estimacion_abandono('computacion', 'Licenciatura en Ciencias de la Computación')

In [15]:
calculo_computacion

,año_inscripcion_facultad,cantidad_inscripciones,cantidad_egresados,tasa_egreso,abandono,tasa_abandono
0,2005,67,24.0,0.358209,43.0,0.641791
1,2006,70,26.0,0.371429,44.0,0.628571
2,2007,71,30.0,0.422535,41.0,0.577465
3,2008,79,42.0,0.531646,37.0,0.468354
4,2009,85,37.0,0.435294,48.0,0.564706
5,2010,137,59.0,0.430657,78.0,0.569343
6,2011,143,53.0,0.370629,90.0,0.629371
7,2012,135,41.0,0.303704,94.0,0.696296
8,2013,189,57.0,0.301587,132.0,0.698413
9,2014,164,42.0,0.256098,122.0,0.743902
10,2015,171,42.0,0.245614,129.0,0.754386
11,2016,151,28.0,0.185430,123.0,0.814570
12,2017,189,39.0,0.206349,150.0,0.793651
13,2018,190,36.0,0.189474,154.0,0.810526
14,2019,228,40.0,0.175439,188.0,0.824561
15,2020,147,35.0,0.238095,112.0,0.761905
16,2021,470,35.0,0.074468,435.0,0.925532
17,2022,271,7.0,0.025830,264.0,0.974170
18,2023,308,NaN,NaN,NaN,NaN
19,2024,336,NaN,NaN,NaN,NaN
20,2025,326,NaN,NaN,NaN,NaN

In [16]:
calculo_15_años_computacion[['año_inscripcion_facultad', 'cantidad_inscripciones', 'egresados_en_15_anios_o_menos', 'abandono_15_años', 'tasa_egreso_15_años_con_d', 'tasa_abandono_15_años_con_d', 'd_del_año', 'error_d']]

,año_inscripcion_facultad,cantidad_inscripciones,egresados_en_15_anios_o_menos,abandono_15_años,tasa_egreso_15_años_con_d,tasa_abandono_15_años_con_d,d_del_año,error_d
0,2005,67,21.0,46.0,0.324316,0.675684,0.044776,0.010054
1,2006,70,23.0,47.0,0.339980,0.660020,0.042857,0.008135
2,2007,71,28.0,43.0,0.408059,0.591941,0.028169,-0.006553
3,2008,79,39.0,40.0,0.510812,0.489188,0.037975,0.003252
4,2009,85,35.0,50.0,0.426062,0.573938,0.023529,-0.011193
5,2010,137,57.0,80.0,0.430505,0.569495,0.014599,-0.020124
6,2011,143,53.0,90.0,0.383498,0.616502,0.000000,-0.034722

In [17]:
calculo_15_años_computacion['tasa_egreso_15_años_con_d'].mean()

np.float64(0.4033190267164963)

In [18]:
calculo_15_años_computacion['tasa_abandono_15_años'].mean()

np.float64(0.610215168810903)

## Promedio general

In [19]:
total_inscripciones = (calculo_15_años_computacion['cantidad_inscripciones'].sum() + calculo_15_años_biologia['cantidad_inscripciones'].sum() + calculo_15_años_fisica['cantidad_inscripciones'].sum())
total_egresados = (calculo_15_años_computacion['egresados_en_15_anios_o_menos'].sum() + calculo_15_años_biologia['egresados_en_15_anios_o_menos'].sum() + calculo_15_años_fisica['egresados_en_15_anios_o_menos'].sum())
total_egresados/total_inscripciones

np.float64(0.5035727717186912)

promedio ponderado

In [20]:
egresados_compu = calculo_15_años_computacion['egresados_en_15_anios_o_menos'].sum()
egresados_biologia = calculo_15_años_biologia['egresados_en_15_anios_o_menos'].sum()
egresados_fisica = calculo_15_años_fisica['egresados_en_15_anios_o_menos'].sum()

calculo_15_años_computacion['tasa_egreso_15_años_con_d'].mean() * egresados_compu/total_egresados + calculo_15_años_biologia['tasa_egreso_15_años_con_d'].mean() * egresados_biologia/total_egresados + calculo_15_años_fisica['tasa_egreso_15_años_con_d'].mean() * egresados_fisica/total_egresados

np.float64(0.516328990075307)

# Analisis de pandemia

Estimamos la cantidad de egresados de 2019 y 2020 y vemos la variacion

In [21]:
estimacion_2019_compu, estimacion_2020_compu, variacion_compu = estimacion_egresados_2019_vs_2020('computacion')
estimacion_2019_fisica, estimacion_2020_fisica, variacion_fisica = estimacion_egresados_2019_vs_2020('fisica')
estimacion_2019_biologia, estimacion_2020_biologia, variacion_biologia = estimacion_egresados_2019_vs_2020('biologia')

In [22]:
estimacion_2019_compu, estimacion_2020_compu, variacion_compu

(np.float64(52.770833333333336),
 np.float64(43.458333333333336),
 np.float64(0.1764705882352941))

In [23]:
estimacion_2019_fisica, estimacion_2020_fisica, variacion_fisica

(np.float64(58.13352272727273),
 np.float64(43.89488636363637),
 np.float64(0.2449298734300933))

In [24]:
estimacion_2019_biologia, estimacion_2020_biologia, variacion_biologia

(np.float64(134.3218085106383),
 np.float64(96.125),
 np.float64(0.2843678843678844))

si hacemos las 3 carreras juntas.

In [25]:
estimacion_2019 = estimacion_2019_compu + estimacion_2019_fisica + estimacion_2019_biologia
estimacion_2020 = estimacion_2020_compu + estimacion_2020_fisica + estimacion_2020_biologia
variacion = (estimacion_2019 - estimacion_2020)/estimacion_2019

estimacion_2019, estimacion_2020, variacion

(np.float64(245.22616457124437),
 np.float64(183.4782196969697),
 np.float64(0.2517999862789329))